version: '3.8'

services:
  musiclink:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musiclink
    ports:
      - "9911:8000"
    volumes:
      # Монтируем папку tracks, чтобы можно было добавлять треки без пересборки
      - ./tracks:/app/tracks
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
